xbmc/addon-check

- check_addon.py
Fix for image and xml access going wrong on:
- XML not valid, e.g. tag not closed
- Image broken format
> Make sure xml/image access doesn't crash the runner

- README.md
- check_addon.py
- check_repo.py
Added file_index concept and try to parse all xml files + open all graphics to check for errors
Closes #3
> Refactor private vs public methods and naming.

- check_addon.py
> Replace blacklisting with a whitelisting approach

- check_repo.py
> Add option to set toplevel folders via parameters from the outside world

- .travis.yml
- check_addon.py
- common.py
- tests/fixtures/.tests-config.json
- tests/test_common.py
> Add leia deprecations and tests

- check_addon.py
- check_repo.py
Fixes #13 
Before this log output used to look like:
```
PROBLEM: Invalid xml found. /home/travis/build/xbmc/repo-plugins/
plugin.video.reddit_viewer/resources/settings.xml
```
After applying these changes log output will look like:
```
PROBLEM: Invalid xml found. /xbmc/repo-plugins/
plugin.video.reddit_viewer/resources/settings.xml
```
> Strip Repository path from logs

- check_addon.py
- check_repo.py
- common.py
- tests/test_common.py
Fixes #39 
made changes according to PEP style guide.
> Fixes #39  Reformatting the code according to PEP style guide.

- .gitignore
- check_addon.py
- check_repo.py
- git_comments.py
Fixes #39
made changes according to PEP style guide and added .idea/ to gitignore.
> Fixes #39 Reformatting the code according to PEP style 

- .travis.yml
- check_addon.py
This will check for the pep8 violation.
Also I have fixed all the errors that were there in code base.
@Razzeee Should I change the value of length parameter from 120 to soemthing less or is it OK ?
> PEP 8 All Code

- .vscode/launch.json
- kodi_addon_checker/check_repo.py
@slgobinath Will you implement a repo parameter or should I look at it?
> Add launch.json config for vscode & always report when finished

- .travis-addon.yml.example
- .travis-repo.yml.example
- setup.py
Check addon example is not tested at the moment.
> Update travis examples and short summary

- setup.py
Preparation to release a new version.
> Prepare new release and ignore test folders for releases

- .travis-addon.yml.example
- .travis-repo.yml.example
- .travis.yml
- kodi_addon_checker/check_addon.py
- setup.py
Due to None being passed to the methods
> Fix looseversion error

- kodi_addon_checker/__main__.py
- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_repo.py
Fix #56 
@Razzeee This contain some code similar to PR [51](https://github.com/xbmc/addon-check/pull/51).
Should I make this also usable via `.tests-config.json` ?
> Add check for existing addon

- kodi_addon_checker/check_addon.py
We were parsing same addon.xml file multiple time. so I have made changes to parse the file only at one place and then pass that parsed file as a parameter to all the function.
> Remove multiple parsing of addon.xml

- kodi_addon_checker/check_addon.py
Fix #83
I have added all the names of pseudo addons to the ignore list
> Update ignored list of pseudo addons.

- kodi_addon_checker/__init__.py
- tests/test_check_addon.py
This is an integration test for the kodi-addon-checker tool.
I have made the import for the `__main__.py`  in `__init.py` file because it is consider a bad practice to do something like: `from __main__ import foo`.
> Tests for kodi-addon-checker

- .travis-repo.yml.example
- .vscode/launch.json
- kodi_addon_checker/__main__.py
- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_repo.py
- tests/test_check_addon.py
I have added a new PR argument. This will add an optional argument of running the tool on a pull requests. It will be helpful in running a whole repo check and adding other functionality.
**NOTE**
Right After this Pull get merged I will update the tests
> Add PR argument

- kodi_addon_checker/check_repo.py
I have added multiple error as just using bare except was too vague and possibly we can expect multiple exceptions from our checks.
> catch exceptions per addon for a repo check

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_artwork.py
- kodi_addon_checker/check_dependencies.py
- kodi_addon_checker/check_entrypoint.py
- kodi_addon_checker/check_files.py
- kodi_addon_checker/check_old_addon.py
- kodi_addon_checker/check_string.py
- kodi_addon_checker/common.py
- kodi_addon_checker/handle_files.py
I have refactored the code and have broken the functions into different files. I have made so many files because I think this will increase the maintainability.
For example handle_files.py file contains all the functions that will never have to be touched again.
This is the new structure of our code base:
* handle_files.py (This deals with file, find any file or create multiple files)
- find_file()
- find_file_recursive()
- create_file_index()
- find_in_file
- addon_file_exists (search for addon file only)
* Check_files.py (checks all the files/folders like addon.xml,any json file )
- check_for_invalid_xml
- check_for_invalid_json
- check_addon_xml
- addon_xml_matches_folder
- check_for_legacy_language_path
- check_file_whitelist
* check_artwork.py (checks all the images, artworks or …
> Refactoring Codebase

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_artwork.py
- kodi_addon_checker/check_dependencies.py
- kodi_addon_checker/check_entrypoint.py
- kodi_addon_checker/check_files.py
- kodi_addon_checker/check_old_addon.py
- kodi_addon_checker/check_repo.py
- kodi_addon_checker/check_string.py
- kodi_addon_checker/handle_files.py
- kodi_addon_checker/report.py
- kodi_addon_checker/reporter.py
I have made all the normal imports i.e `from kodi_addon_checker.commom import relative_path` to relative imports i.e `from.common import relative_path`
> change normal imports to relative imports

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/common.py
Remove Unused import logger from check_addon.py
Remove Unused variable 'importer' from common.py
> Remove unused variable and import

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_dependencies.py
> Update dependency ignore list

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_py3_compatibility.py
- requirements.txt
This will help in detecting the python2 code in addons submitted. 
Currently the output format for this is sloppy.
> Add check for Python3 compatibility of addons

- kodi_addon_checker/check_addon.py
- script.test/main.py
- tests/fixtures/.tests-config.json
- tests/test_common.py
all supported Kodi versions (Gotham and above) support strings.po
> remove check_legacy_strings_xml config

- kodi_addon_checker/check_artwork.py
- stricter xpath for finding assets
- one fallback indicator is enough
- return a list of strings instead of a list of ElementTree Elements in _assets function
> refactor check_artwork

- README.md
- kodi_addon_checker/check_addon.py
- kodi_addon_checker/schema_validation.py
- kodi_addon_checker/xml_schema/addon.xsd
- kodi_addon_checker/xml_schema/gotham_images.xsd
- kodi_addon_checker/xml_schema/gotham_metadata.xsd
- kodi_addon_checker/xml_schema/gotham_pluginsource.xsd
- kodi_addon_checker/xml_schema/gotham_repository.xsd
- kodi_addon_checker/xml_schema/gotham_scraper.xsd
- kodi_addon_checker/xml_schema/gotham_script.xsd
- kodi_addon_checker/xml_schema/gotham_service.xsd
- kodi_addon_checker/xml_schema/gotham_skin.xsd
- kodi_addon_checker/xml_schema/gotham_uisounds.xsd
- kodi_addon_checker/xml_schema/gotham_webinterface.xsd
- kodi_addon_checker/xml_schema/isengard_contextitem.xsd
- kodi_addon_checker/xml_schema/isengard_language.xsd
- kodi_addon_checker/xml_schema/jarvis_contextitem.xsd
- kodi_addon_checker/xml_schema/krypton_controller.xsd
- kodi_addon_checker/xml_schema/leia_games.xsd
- kodi_addon_checker/xml_schema/leia_repository.xsd
- requirements.txt
- setup.py
Fixes #33 
I have tested many addon.xml files against the schema's but none of them matches.I have taken schema's definitions from [Here](https://github.com/xbmc/xbmc/tree/master/addons)
I am not sure if this is the correct way of doing it or not.I think we'll have to create a new schema for addon.xml but again I am not sure.
Let me know about all the changes that are required.
> Add schema validation

- tests/test_data/File_index/file_index.py
- tests/test_handle_files.py
This contains unit tests for all the function in `handle_files.py` except for `addon_file_exists` function. I tried but couldn't write successful test for that function.
> Add unit test and test data for functions in handle_files.py

- kodi_addon_checker/check_dependencies.py
Fixes #110.
used the existing function, `_get_users_dependencies`, to separate optional and required dependencies.
> Add check for optional dependencies

- README.md
> Alter word 'requirement' to 'requirements' in readme

- kodi_addon_checker/check_addon.py
repository-generator requires a version bump to publish the broken state
fixes #128
> check version (bump) for broken add-ons too

- kodi_addon_checker/check_dependencies.py
those are now in the Kodi (binary) repository
> remove inputstream.* from leia dependencies ignore list

- README.md
- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_files.py
- tests/test_check_files.py
- tests/test_data/Executable file/file_permission.py
- tests/test_data/Non-executable file/file_permission.py
Fixes #43 
I have set this to be reported as a warning, let me know if we have to report it as `error` instead of `warning`.
> Add check for incorrectly set file permissions

- kodi_addon_checker/xml_schema/gotham_metadata.xsd
> Parially revert change that made some tags not able to be empty

- README.md
- kodi_addon_checker/check_dependencies.py
> check presence of extensions in addon dependencies

- README.md
- kodi_addon_checker/plugins/log_reporter.py
Results: https://pastebin.com/AFvzfa91 
The first half is an addon, second is a repo. `ctrl+f` for `*-repo-*` to find the split
> add log reporter

- kodi_addon_checker/__main__.py
- kodi_addon_checker/addons/Addon.py
- kodi_addon_checker/addons/AddonDependency.py
- kodi_addon_checker/addons/Repository.py
- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_artwork.py
- kodi_addon_checker/check_dependencies.py
- kodi_addon_checker/check_entrypoint.py
- kodi_addon_checker/check_files.py
- kodi_addon_checker/check_old_addon.py
- kodi_addon_checker/check_py3_compatibility.py
- kodi_addon_checker/check_repo.py
- kodi_addon_checker/check_string.py
- kodi_addon_checker/check_url.py
- kodi_addon_checker/common.py
- kodi_addon_checker/handle_files.py
- kodi_addon_checker/logger.py
- kodi_addon_checker/plugins/console_reporter.py
- kodi_addon_checker/report.py
- kodi_addon_checker/schema_validation.py
Fixes #171 
I have added docstrings and have sorted the imports in most of the file.
After this most of the error will be related to the snake_case format of argument or variables.
> Sort imports and add docstrings

- setup.py
This module is only compatible with Python 3.
> require at least Python 3.4

- README.md
- kodi_addon_checker/__main__.py
- kodi_addon_checker/logger.py
resolves one of the log files mentioned in #198
> add --enable-debug-log to enable logging to kodi-addon-checker.log

- .pylintrc
- kodi_addon_checker/check_old_addon.py
- kodi_addon_checker/record.py
> resolve pylint too-many-arguments

- .travis.yml
Matrix branches were not being checked by travis on PR submissions
> Add travis checks for Matrix

- kodi_addon_checker/versions.py
A typo introduced in my last pull request. Sorry about that.
The code is not used though.
> Fix typo in versions

- kodi_addon_checker/check_addon_branches.py
- kodi_addon_checker/versions.py
https://travis-ci.org/github/anxdpanic/plugin.video.composite_for_plex/builds/674938982
https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/312/checks
> fix unhashable type

- kodi_addon_checker/check_addon_branches.py
unable pass test with lower branch commits
- Commit to lower branch: https://travis-ci.org/github/anxdpanic/plugin.video.composite_for_plex/builds/674938982
- New version in lower branch: https://travis-ci.org/github/MrSprigster/script.module.python.twitch/builds/674972630
> reduce _check_version_lower to warning when not called for repository pr

- kodi_addon_checker/check_string.py
- tests/test_check_po_files.py
- tests/test_data/PO_files/syntax_error/strings.po
> fix any Gettext automatic comments in the source po before testing with polib

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_dependencies.py
- allow successful test for indevelopment add-on and module combinations
> warn on missing dependency in official repository when not using -PR

- .github/workflows/check-kodi-repos.yml
- kodi_addon_checker/__init__.py
- kodi_addon_checker/check_dependencies.py
Hope this is ok @enen92 . let me know if ive missed something, or just flat out did something wrong.
> Add Omega branches

- kodi_addon_checker/check_addon.py
- kodi_addon_checker/check_dependencies.py
Added a check that prevents add-ons targetting Python 2.
> Added: Reject add-ons targeting Python 2.

- requirements.txt
Refer https://github.com/xbmc/addon-check/pull/271#issuecomment-2132440128
> Update min required version of requests and urllib3
