check_addon.py

Fixes #42 
This will add support of fanart of size 3840*2160.
Adding support for more sizes will be easier now.

add 3840x2160 fanart size

---

check_addon.py
check_repo.py
git_comments.py

It fixes issue #27 
This will help in informing  contributors about the problems in their add-ons.
I have tested it locally but haven't tested it on Travis-CI.

Auto comment on issues found in pull request

---

README.md
setup.py

@Razzeee,
This PR fixes markdown rendering problem in https://pypi.org/project/kodi-addon-checker/
Though the new PyPi Warehouse supports markdown description, you have to use the following commands in the exact order to get expected formatting.
Prerequisite: Upgrade `setuptools` and `twine`
```
sudo pip3 install -U setuptools
sudo pip3 install -U twine
```
Command:
```
python3 setup.py sdist bdist_wheel
twine upload pypitest dist/*.tar.gz
twine upload dist/*.whl
```
Note: This feature is tested on my [personal project](https://test.pypi.org/project/safeeyes/).
I haven't upgraded the version in `setup.py` since this is a minor issue and not necessary to release a new version for this fix.
Also note that a new badge [![PyPI version](https://badge.fury.io/py/kodi-addon-checker.svg)](https:// …

Fix markdown rendering in pypi

---

kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_repo.py
kodi_addon_checker/common.py
kodi_addon_checker/config.py
kodi_addon_checker/plugins/console_reporter.py
kodi_addon_checker/record.py
kodi_addon_checker/report.py
kodi_addon_checker/reporter.py
tests/test_common.py

Hi @Razzeee,
Could you please have a look at this design improvement. This PR improves how addon-checker handles reports. Currently, all reports are printed to the console as you check add-ons. It cannot support multiple reporters (say GitHub reporter, markdown reporter, checkstyle reporter, etc).
This PR isolates reports and reporters into separate modules so that add-on checker can be easily extended to support new reporters in future. For the moment, I have implemented [ConsoleReporter](https://github.com/slgobinath/addon-check/blob/feature-new-architecture/kodi_addon_checker/plugins/console_reporter.py) which is printing the report to the console as we have right now.
The low level [Record](https://github.com/slgobinath/addon-check/blob/feature-new-architecture/kodi_addon_checker/repor …

Improve addon report infrastructure

---

.travis-addon.yml.example
.travis-repo.yml.example
kodi_addon_checker/check_addon.py

Fixes #68 
I have taken an example `.tests-config.json`
```json
{
"check_legacy_language_path": false,
"check_legacy_strings_xml": true,
"check_license_file_exists": true,
"comment_on_pull": false,
"check_dependencies": true,
"check_complex_files": true,
"max_line_count": 50,
}
```
Here function name is `check_complex_files` that gets all the extensions from the addon.xml and performs the check and `max_line_count` stores maximum number of lines allowed that will not raise any 
warning.
@enen92 Please let me know if any changes are required.

Add check for complexity of entry point files

---

kodi_addon_checker/check_addon.py

This was causing some problems when we tried to run on a whole repo, as we have addons that have .py files defined as UtF-8-BOM.
@Rechi  @mzfr

Catch error when parsing py files with radon

---

kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/logger.py

This will help us to debug without messing up the Travis-CI logs. It takes an argument `--log_file` which will be the `path of the log file`. If this argument is not given then by default log file will be created in the current working directory. The name of the log file is `kodi-addon-checker.log`.
The output in the log file will look like:
```
2018-05-31 14:16:38 INFO:kodi_addon_checker.check_addon:start: Hello logging
```
**Note**
Right now there is no logging set in any of the file. But we'll be able to use this logger in future.

Create a logger for debugging

---

.travis.yml
requirements.txt
setup.py

We are planning to use pipenv for maintaining dependencies but until then we'll be using requirements.txt file.
.travis.yml is updated for installing all the requirements from requirements.txt file

use requirements.txt file for dependencies

---

kodi_addon_checker/check_addon.py

Fix #82 
I have created a new function for counting the lines of `.xml` file.
Now I have added a check that if extension of a file is `.xml` then it will be passed to the new functions i.e `number_of_line_for_xml` for counting the line.
Ony files with `.py` extension will be passed to radon for parsing.
**Note** 
I was not sure what should be the max_entry_point for xml file so I used the default one. Please let me know if we want to use another variable for it. Also should it be fixed value or should we pass it from config ?

Check complex entry point for xml file

---

kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py

So we were having some issue with having an import in `__init__.py` file. So now we are shifting the `_all_repo_addons` out of the `__main__.py` file. 
There will be no change in the behaviour of the code base

Move all_repo_addons function out of __main__.py

---

README.md
kodi_addon_checker/check_dependencies.py

This will check for the version of `xbmc.python` in addon.xml file according to the kodi version

Add check for xbmc.python version

---

kodi_addon_checker/check_py3_compatibility.py

After searching I found out that tabulate's `pipe` format is quite similar to GFM table format. Will try other formats if this one also doesn't fix the breaking table.

Change table format

---

kodi_addon_checker/check_artwork.py

Fixes #30 
This is a simple check but if we want to check width/height of the screenshot or as said by @enen92 check aspect ratio then I'll make a new function for checking screenshot just like `_check_fanart` or `_check_icon`

check transparency in screenshot

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_files.py
script.test/main.py
tests/fixtures/.tests-config.json
tests/test_common.py

`.tests-config.json` isn't loaded from the current working directory, but from the addon or repo path. That causes that our PR builds aren't checked for legacy language paths.

convert check_legacy_language_path config to branch checks

---

kodi_addon_checker/schema_validation.py
kodi_addon_checker/xml_schema/gotham_pythonscript.xsd

See title.
Right now we are using the `script.xsd` schema file for `xbmc.python.script` addons and for all other scripts like `script.modules`, `screensavers`, etc. A user submitted a script.module/python library with the provides element defined and it passed CI without raising any error. In my opinion we should avoid such things passing unnoticed.
Ref: https://github.com/xbmc/repo-scripts/pull/921

[schema validation] Only xbmc.python.script has provides tag

---

kodi_addon_checker/xml_schema/leia_service.xsd

In https://github.com/xbmc/xbmc/pull/13796 the old `start` attribute was removed due to profiles rework. Now all services start on login and are stopped on logout. Schemas should reflect those changes.
IMO apart from correctness this will also inform users that may be unaware of the change when they submit to Leia.

[schemas] Start option was removed for leia service.addons and defaults to login

---

LICENSES/GPL-3.0-only
LICENSES/README.md
kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_artwork.py
kodi_addon_checker/check_dependencies.py
kodi_addon_checker/check_entrypoint.py
kodi_addon_checker/check_files.py
kodi_addon_checker/check_old_addon.py
kodi_addon_checker/check_py3_compatibility.py
kodi_addon_checker/check_repo.py
kodi_addon_checker/check_string.py
kodi_addon_checker/common.py
kodi_addon_checker/config.py
kodi_addon_checker/handle_files.py
kodi_addon_checker/logger.py
kodi_addon_checker/plugins/array_reporter.py
kodi_addon_checker/plugins/console_reporter.py
kodi_addon_checker/record.py
kodi_addon_checker/report.py
kodi_addon_checker/reporter.py
kodi_addon_checker/schema_validation.py

Fixes #134 
I have added the small license header in all the python files in the tools. 
Should I also add the headers to [test files](https://github.com/xbmc/addon-check/tree/master/tests) and [test addon](https://github.com/xbmc/addon-check/tree/master/script.test)?
Also in the header will it be `Copyright (C) 2018-2018 Team Kodi` or `Copyright (C) 2005-2018 Team Kodi`?

Add license header to all python files.

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_files.py
kodi_addon_checker/handle_files.py
tests/test_check_files.py

Skip `.git` folder, which is inside the add-on path for single add-on repos (upstream repos), for for permission and whitelist checks.
fixes #123

ignore .git folder in create_file_index

---

README.md
kodi_addon_checker/addons/Addon.py
kodi_addon_checker/addons/AddonDependency.py
kodi_addon_checker/addons/Repository.py
kodi_addon_checker/addons/__init__.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_dependencies.py
kodi_addon_checker/check_old_addon.py
script.test/main.py

fixes #124
@MartijnKaijser is it correct to only warn for add-ons which have `script.module.*` as id?

add reverse dependencies check

---

kodi_addon_checker/handle_files.py

Ignore some hidden files and folders

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_py3_compatibility.py

This will report python syntax incompatibilities as error for all versions. The new syntax of those checks was backported to Python 2.6 and therefore is compatible with Gotham and newer.

2to3: split fixers into required and suggested

---

README.md
kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_files.py
kodi_addon_checker/check_repo.py
tests/test_check_addon.py

w/ arg:
```INFO: Addon id and folder name does not match. Ensure folder name is <addon_id> when submitting a PR to Kodi's official repository.```
w/o arg:
```ERROR: Addon id and folder name does not match.```

add argument --allow-folder-id-mismatch to report addon_xml_matches_folder as INFO

---

kodi_addon_checker/check_py3_compatibility.py
requirements.txt

This makes the output easier to read and understand. It can also get applied with the patch command easily.
Additionally it also handles changes of multi line statements correctly.
```
INFO: Checking add-on plugin.image.flickr
[...]
ERROR: ./plugin.image.flickr/default.py
|   # | Existing Code       | Changes required       |
|----:|:--------------------|:-----------------------|
| 866 | except HTTPError,e: | except HTTPError as e: |
| 872 | except URLError,e:  | except URLError as e:  |
ERROR: ./plugin.image.flickr/flickrapi/__init__.py
|   # | Existing Code                                                              | Changes required                                                           |
|----:|:---------------------------------------------------------------------------|:--------- …
```

[check] 2to3: output changes as diff

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_artwork.py

Implicit fanart.jpg and icon.png in the root of the add-on directory was superseded by the explicit `assets.fanart` and `assets.icon` declarations in Kodi Krypton 17 with xbmc/xbmc#10060. There is a bit of awkward backward compatibility in Kodi core that extends to add-on lists in skins with the implicit artwork, so I'd like to generally require "assets" be used for further submissions so this back-compat can be removed at some point.
Noted on the wiki pages [Add-on structure#icon.png](https://kodi.wiki/view/Add-on_structure#icon.png) and [Addon.xml#&lt;assets&gt;](https://kodi.wiki/view/Addon.xml#.3Cassets.3E).
It should also be noted in the forums.

require icon/fanart be explicitly declared in addon.xml assets

---

kodi_addon_checker/check_py3_compatibility.py

This will continue the remaining addon check (check_addon.py) process if `lib2to3.pgen2.parse.ParseError` exception is thrown during the 2to3 check.

[fix] 2to3: catch parse exception

---

.pylintrc
.travis.yml

#173 
**Note:** It will not pass the build. We will have to correct it. I have created new issue for it. #175

Switched from pycodestyle to pylint

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_old_addon.py

This will fix the missing error report about version being equal or lower, if the version is greater than the version in the lowest repo containing the add-on.

[fix] iterate over repos in reverse order in check_for_existing_addon

---

kodi_addon_checker/plugins/log_reporter.py

resolves one of the log files mentioned in #198

only create kodi-addon-checker-report.log when using --reporter=log

---

setup.py

Python 3.4 has reached end-of-life in March 2019

require at least Python 3.5

---

kodi_addon_checker/check_dependencies.py

This will make the addon-checker report a problem if submitting addons to matrix with versions lower than 3.0.0
@Razzeee it would be nice if you could create a new release.

Prepare xbmc.python for matrix

---

kodi_addon_checker/addons/Repository.py

This should reduce the connection timeout issues on PR's
The connection to the failing mirrors have required ~20 seconds in the occurrences I've checked.

increase repository request timeout to 30 seconds

---

kodi_addon_checker/check_artwork.py
kodi_addon_checker/xml_schema/gotham_metadata.xsd

As a result of https://github.com/xbmc/repo-scripts/pull/1299 we need to start checking the other art types missing because they can break our repository generator script.
We discussed and agreed on the new rules for clearlogo, banner and screenshot asset types in https://forum.kodi.tv/showthread.php?tid=351853. Wiki has already been updated too:
https://kodi.wiki/view/Addon.xml
https://kodi.wiki/view/Add-on_structure#resources.2Ffanart.jpg

Add checks for all missing asset art types

---

kodi_addon_checker/addons/Repository.py

If a repository times out or has other connectivity issues, this change ensures the request is retried, trying other repositories when available (round robin).

Retry unreliable repositories

---

kodi_addon_checker/addons/AddonDependency.py
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_artwork.py
kodi_addon_checker/check_dependencies.py
kodi_addon_checker/check_old_addon.py
kodi_addon_checker/check_py3_compatibility.py
kodi_addon_checker/versions.py
script.test/main.py
tests/test_versions.py

To fix https://github.com/xbmc/repo-scripts/pull/1356
`distutils.version` is not a robust way to do version comparison. This has been already raised to python core and the patch was denied: https://bugs.python.org/issue30272
This changes the implementation to rely on `packaging.version` which has a much more robust algorithm.
This PR also changes `KodiVersion.py` to `versions.py` for consistency. `LooseVersion` is now `AddonVersion` and centralized on `versions.py`. Tests added to make sure this won't break in the future.

Improve addon-checker version comparison

---

requirements.txt

Travis seems to fail in some cases with current master. `ModuleNotFoundError: No module named 'packaging'`
https://travis-ci.org/github/MrSprigster/script.module.python.twitch/builds/668141515?utm_source=github_status&utm_medium=notification

add packaging to requirements

---

kodi_addon_checker/versions.py

When the addon-checker errors out due to a dependency version mismatch, the `AddonVersion` object should return the version as a string and not the object itself. Fixes a minor identified by @anxdpanic in https://travis-ci.org/github/MrSprigster/Twitch-on-Kodi/builds/668410076#L269

Improve version mismatch representation

---

kodi_addon_checker/check_files.py
kodi_addon_checker/common/__init__.py
kodi_addon_checker/common/decorators.py
tests/test_check_files.py

There is no need to check for file permissions on windows. It now shows a lot of errors because all files are executable on Windows.

Don't check for file permissions on Windows

---

kodi_addon_checker/versions.py
tests/test_versions.py

Fixes https://github.com/xbmc/addon-check/issues/224
Kodi supports non-PEP440 compliant version for development purposes, eg:
`1.0.1~beta`
`1.0.1~beta01`
etc
As those are not PEP440 compliant, the `packaging.version` module parses the version to `LegacyVersion` objects instead of `Version` objects. When the comparator compares both objects, `LegacyVersion` is always lower.
This is solved by ensuring that when a version string like those above is supplied to addon-checker (thus containing `~alpha` or `~beta`) and the resulting object is a `LegacyVersion`, the `AddonVersion` class does an implicit conversion to the PEP440 format: `x.x.xalphay`.
Tests added to mimic the ones in Kodi.

[Versions] Support legacy non-compliant PEP440 development versions 

---

kodi_addon_checker/check_artwork.py

Since @anxdpanic added file size checks for artwork, there's absolute no reason to force developers to use .jpg files for screenshots and banners.
Wiki has already been edited:
https://kodi.wiki/view/Add-on_structure#resources.2Fscreenshot-x.jpg_.28optional.29
https://kodi.wiki/view/Add-on_structure#resources.2Fbanner.jpg_.28optional.29

[Artwork] Allow screenshots and banners in png

---

kodi_addon_checker/check_files.py

We have webinterface addons and other addons that also include webinterfaces. They include favicons, so make sure .ico extension is whitelisted

Add .ico to whitelist (favicon.ico)

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_files.py
script.test/main.py

Currently we only check if in versions higher or equal to isengard the addon includes the new language folder layout. However, we don't to anything for version between gotham and isengard. If an addon update sends a "new folder layout" for gotham and helix, kodi won't be able to use them, so error out.

Improve language folder layout check for versions below isengard

---

kodi_addon_checker/xml_schema/matrix_contextitem.xsd

I added an option to validate that the context menu items in the addon.xml do not define duplicate `library` parameters (for Leia and down) or `library`/`args` combinations for Matrix (See https://github.com/xbmc/xbmc/pull/17631)

Added check for duplicate context menu libraries/args

---

kodi_addon_checker/check_addon.py
kodi_addon_checker/check_addon_branches.py
kodi_addon_checker/check_dependencies.py

Unfortunately the last approach do not work for all addons, causing problems in the repo-scrappers repository. The repository generator places clones of the same addon on upper branches if their dependencies are abi backwards compatible.
Means that if you push a xml scrapper to gotham branch, the same version will also be available in matrix branch (I mean in the addons.xml.gz and not in github). Addon-checker errors out because it sees the matrix addon as non-migration compatible (same addon version). This happens because we are blindly making that decision on the fact `xbmc.python` is not forward compatible between target and matrix - but the addon might not depend on xbmc.python at all.
So this PR changes the check to make it more generic, it looks over all the xbmc api dependencies …

Improve forward-version/migration checks

---

kodi_addon_checker/check_dependencies.py

I have changed the ignore script.module.pycryptodome dependency to include all releases from Leia and later versions
only after this i can successfully get right result in the test buildings flow
change tested locally, flow: https://github.com/CastagnaIT/plugin.video.netflix/runs/1077732346
Ref Issue: #241

Ignore script.module.pycryptodome dependency from Leia and later versions

---

kodi_addon_checker/check_addon_branches.py

Condition should only be evaluated if a PR is being performed otherwise we are reporting errors for regular CI workflows (e.g. checks after a PR or merge to master)

Simplify and fix condition for addon versions

---

kodi_addon_checker/check_files.py
tests/test_check_files.py

A `.gitignore` file should no longer be present in the submissions.

Changed: No longer ignore the .gitignore file extension.

---

kodi_addon_checker/check_addon.py

Addon checker is throwing if invalid xml data is present in addon xml.
Catch the exception and log a problem instead.

Report the problem if the addon.xml xml contents are invalid

---

README.md
kodi_addon_checker/check_addon.py
kodi_addon_checker/check_allowed_versions.py
tests/test_allowed_versions.py

Follow up to https://github.com/xbmc/repository-generator/pull/16, this makes addon-checker validate the provided version in addon.xml against the regex used in repository-generator. This makes sure the checker catches any invalid version in advance

Check if addon version is compliant with repository generator

---

.github/workflows/test_and_lint_matrix.yml

We cannot use travis anymore, so start migrating our old CI to github actions. It's important pytest is able to run against any open pull request to avoid regressions.

Build, test and lint using github actions

---

kodi_addon_checker/versions.py

Drop the usage of LegacyVersion: ttps://github.com/https://github.com/pypa/packaging/pull/407
Also testing the new CI.

Remove usage of packaging.LegacyVersion (removed in py3.11)

---

kodi_addon_checker/schema_validation.py
kodi_addon_checker/xml_schema/gotham_images.xsd
kodi_addon_checker/xml_schema/leia_font.xsd

See https://github.com/xbmc/repo-resources/pull/392 . Font addons were added in Leia by @notspiff (see https://github.com/xbmc/xbmc/pull/12130)
Also drops the "compile" arg support for image addons, this is not supported in the code.

Adds support for font addons 

---

kodi_addon_checker/addons/Repository.py

Rate limiting has been added to mirrors.kodi.tv which the multiple requests for the various repository addons.xml.gz will trigger.
This adds some rate limiting, error handling and retry backoff to avoid the rate limit resulting in the addon checker failing

Rate limit requests for addons.xml.gz

---

kodi_addon_checker/check_files.py

Fixes issue #275 
* Correctly check for file extension instead of looking for an extension anywhere in the full filename

XML/JSON Correctly check for file extension

---

README.md
kodi_addon_checker/__main__.py
kodi_addon_checker/check_addon.py

Adds an option to ignore dependency checks.
The reason for this is outlined in #263.
Closes #263.

Add option `skip-dependency-checks`
